# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TradPlusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TradPlusAdSDK', '13.2.0'
  pod 'TradPlusAdSDK/AdMobAdapter', '13.2.0'
  pod 'Google-Mobile-Ads-SDK','12.0.0'
  pod 'TradPlusAdSDK/BigoAdapter', '13.2.0'
  pod 'BigoADS','4.6.0'
  pod 'TradPlusAdSDK/VungleAdapter', '13.2.0'
  pod 'VungleAds', '7.4.3'
  pod 'TradPlusAdSDK/MintegralAdapter', '13.2.0'
  pod 'MintegralAdSDK' ,'7.7.2'
  pod 'MintegralAdSDK/All','7.7.2'
  pod 'TradPlusAdSDK/PangleAdapter', '13.2.0'
  pod 'Ads-Global', '6.4.0.6'
  
  pod 'AppHarbrSDK','1.20.2'
end
