# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TradPlusDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TradPlusAdSDK', '12.2.0'
  pod 'TradPlusAdSDK/FacebookAdapter', '12.2.0'
  pod 'FBAudienceNetwork','6.15.2'
  pod 'TradPlusAdSDK/AdMobAdapter', '12.2.0'
  pod 'Google-Mobile-Ads-SDK','11.8.0'
  pod 'TradPlusAdSDK/AppLovinAdapter', '12.2.0'
  pod 'AppLovinSDK','12.6.1'
  pod 'TradPlusAdSDK/IronSourceAdapter', '12.2.0'
  pod 'IronSourceSDK','8.3.0'
  pod 'TradPlusAdSDK/MintegralAdapter', '12.2.0'
  pod 'MintegralAdSDK' ,'7.7.1'
  pod 'MintegralAdSDK/All','7.7.1'
  pod 'TradPlusAdSDK/GDTMobAdapter', '12.2.0'
  pod 'GDTMobSDK', '4.15.00'
  pod 'TradPlusAdSDK/PangleAdapter', '12.2.0'
  pod 'Ads-Global', '6.2.0.5'
  pod 'TradPlusAdSDK/CSJAdapter', '12.2.0'
  pod 'Ads-CN', '6.3.1.0'
  
  pod 'AppHarbrSDK'
end
